workflows:
  ios_ipa:
    name: iOS IPA (FIXED)

    environment:
      flutter: stable
      xcode: latest

    working_directory: my_app

    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ipa --no-codesign

    artifacts:
      - build/ios/ipa/**/*.ipa
