workflows:
  ios_ipa:
    name: iOS IPA Simple

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ipa --no-codesign

    artifacts:
      - build/ios/ipa/**/*.ipa
