workflows:
  ios:
    environment:
      flutter: stable

    working_directory: my_app

    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app
